---
title: "iButton 2019 Analysis"
output: html_notebook
---

## 2019 iButton Data
```{r}
library(ggrepel)
library(ggthemes)
library(tidyverse)
load(file="./data/2019_iButtons_by_day_1m.RData")
my.ylab = expression(atop(paste("Mean Daily Water Temperature, ", degree,"C"), "(+/- Min., Max.)"))
p <- ggplot(subset(sum_by_site_1m, water %in% c("water")), mapping = aes(x = dist_in_sound, y = mean_mean_daily_temp_c)) +
  geom_point() +
  geom_pointrange(aes(ymin=mean_min_daily_temp_c, ymax=mean_max_daily_temp_c)) +
  geom_smooth(method=lm) +
   labs(y= my.ylab, x = "Distance into sound (m)")
  
p + theme_classic()



```

## 1980s Druehl NO3 Data

```{r}
load(file="./data/Druehl_no3_1980.RData")


druehl_nutrients_1980_means <- druehl_nutrients_1980 %>% group_by(site, depth, month) %>% summarize(mean_no3 = mean(no3, na.rm = T))

druehl_nutrients_1980_means <- druehl_nutrients_1980_means  %>% 
  left_join(sites, by = "site")
druehl_nutrients_1980_means$dist_sound_km <- druehl_nutrients_1980_means$dist_sound/1000

nutrients.means.0m <- filter(druehl_nutrients_1980_means, depth == 0)
nutrients.means.4m <- filter(druehl_nutrients_1980_means, depth == 4)

ggplot(nutrients.means.4m, aes(x = dist_sound_km,y=mean_no3)) + geom_point()

```

## Macro and Nereo Health and Growth

```{r}
load(file="./data/Health_and_Growth_2020.RData")

p1<- ggplot(macro_health, aes(x = dist_sound_km, y = mean_gray_value)) +
  ylim(100,200) + xlim (3,15) +
  labs(x = "", y = expression(paste("Blade bleaching index"))) +
  geom_point() +
  theme_classic() +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

#example model output for these data
library(lme4)
mixed.lmer1 <- lmer(mean_gray_value ~ dist_sound_km + (1|site/ind_no), data = macro_health)

p2 <- ggplot(macro_growth, aes(x = dist_sound_km, y = net_blade_growth)) +
  labs(x = "", y = expression(paste("Net blade growth/day (cm)"))) +
  xlim (3,15) +
  geom_point() +
  theme_classic() +
  geom_hline(yintercept=0, linetype = "dashed", color = "darkgray") +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p3 <- ggplot(macro_growth, aes(x = dist_sound_km, y = frond_growth)) +
  labs(x = "", y = expression(paste("Frond growth/day (cm)"))) +
  xlim (3,15) +
  geom_point() +
  theme_classic() +
  geom_hline(yintercept=0, linetype = "dashed", color = "darkgray") +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p4 <- ggplot(nereo_health, aes(x = dist_sound_km, y=blade_no)) +
  labs(x = "", y = "Number of blades") +
  xlim (3,15) +
  geom_point() +
  theme_classic() +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p5 <- ggplot(nereo_health, aes(x = dist_sound_km, y=mean_blade_len)) +
  labs(x = "Distance from open coast (km)", y ="Mean blade length (cm)") +
  geom_point() +
  xlim (3,15) +
  theme_classic() +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

#make blank plot for 6th panel
p6 <- frame()

#final plot
library(ggpubr)
figure <- ggarrange(p1, p3, p2, p4, p5, p6, labels = letters[seq( from = 1, to = 6 )],ncol = 3, nrow = 2)
figure
ggsave("health_growth_fig.pdf", width = 9, height = 6)



```

