---
title: "Health and Growth"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Macro and Nereo Health and Growth Plots

```{r}

load(file="../data/health_growth/Health_and_Growth_2020.RData")


p1<- ggplot(macro_health, aes(x = dist_sound_km, y = mean_gray_value)) +
  ylim(100,200) + xlim (3,15) +
  labs(x = "", y = expression(paste("Blade bleaching index"))) +
  geom_point() +
  theme_classic() +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p2 <- ggplot(macro_growth, aes(x = dist_sound_km, y = net_blade_growth)) +
  labs(x = "", y = expression(paste("Net blade growth/day (cm)"))) +
  xlim (3,15) +
  geom_point() +
  theme_classic() +
  geom_hline(yintercept=0, linetype = "dashed", color = "darkgray") +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p3 <- ggplot(macro_growth, aes(x = dist_sound_km, y = frond_growth)) +
  labs(x = "", y = expression(paste("Frond growth/day (cm)"))) +
  xlim (3,15) +
  geom_point() +
  theme_classic() +
  geom_hline(yintercept=0, linetype = "dashed", color = "darkgray") +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p4 <- ggplot(nereo_health, aes(x = dist_sound_km, y=blade_no)) +
  labs(x = "", y = "Number of blades") +
  xlim (3,15) +
  geom_point() +
  theme_classic() +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

p5 <- ggplot(nereo_health, aes(x = dist_sound_km, y=mean_blade_len)) +
  labs(x = "Distance from open coast (km)", y ="Mean blade length (cm)") +
  geom_point() +
  xlim (3,15) +
  theme_classic() +
  geom_smooth(method="lm", alpha = 0.15, color = "black") +
  theme(legend.position = "none") +
  theme (plot.margin=unit(c(0.5,0,0,1), "cm"))

#make blank plot for 6th panel
p6 <- frame()

#final plot
library(ggpubr)
figure <- ggarrange(p1, p3, p2, p4, p5, p6, labels = letters[seq( from = 1, to = 6 )],ncol = 3, nrow = 2)
figure
ggsave("../figures/health_growth_fig.pdf", width = 9, height = 6)



```

## Macro blade bleaching analysis

```{r}
library(tidyverse)
macro_health_tbl<-read_csv(file= "../data/health_growth/macro_health_all.csv")

library(lme4)
mixed.lmer <- lmer(mean_gray_value ~ dist_sound_km + (1|site/ind_no), data=macro_health_tbl)
summary(mixed.lmer)

full.lmer <- lmer(mean_gray_value ~ dist_sound_km + (1|site/ind_no), data=macro_health_tbl, REML = FALSE)
reduced.lmer <- lmer(mean_gray_value ~ 1 + (1|site/ind_no), data=macro_health_tbl, REML = FALSE)
anova(full.lmer, reduced.lmer)

library (AICcmodavg)
AICc(full.lmer)
AICc(reduced.lmer)

```

## Macro growth analysis
```{r}
#example model output for these data
library(lme4)

#Net Blade Growth
mixed.lmer <- lmer(net_blade_growth ~ dist_sound_km + (1|site), data=macro_growth)
summary(mixed.lmer)
 
full.lmer <- lmer(net_blade_growth ~ dist_sound_km + (1|site), data=macro_growth, REML = FALSE)
reduced.lmer <- lmer(net_blade_growth ~ 1 + (1|site), data=macro_growth, REML = FALSE)
anova(full.lmer, reduced.lmer)
 
library (AICcmodavg)
AICc(full.lmer)
AICc(reduced.lmer)

#Frond Growth
mixed.lmer <- lmer(frond_growth ~ dist_sound_km + (1|site), data=macro_growth)
summary(mixed.lmer)
 
full.lmer <- lmer(frond_growth ~ dist_sound_km + (1|site), data=macro_growth, REML = FALSE)
reduced.lmer <- lmer(frond_growth ~ 1 + (1|site), data=macro_growth, REML = FALSE)
anova(full.lmer, reduced.lmer)
 

AICc(full.lmer)
AICc(reduced.lmer)
```
 
## Nereo Growth and Health

```{r}

#Nereo Blade Number
mixed.lmer <- lmer(blade_no ~ dist_sound_km + (1|site), data=nereo_health)
summary(mixed.lmer)
 
full.lmer <- lmer(blade_no ~ dist_sound_km + (1|site), data=nereo_health, REML = FALSE)
reduced.lmer <- lmer(blade_no ~ 1+ (1|site), data=nereo_health, REML = FALSE)
anova(full.lmer, reduced.lmer)

AICc(full.lmer)
AICc(reduced.lmer)

#Nereo Mean Blade Length
mixed.lmer <- lmer(mean_blade_len ~ dist_sound_km + (1|site), data=nereo_health)
summary(mixed.lmer)
 
full.lmer <- lmer(mean_blade_len ~ dist_sound_km + (1|site), data=nereo_health, REML = FALSE)
reduced.lmer <- lmer(mean_blade_len ~ 1+ (1|site), data=nereo_health, REML = FALSE)
anova(full.lmer, reduced.lmer)

AICc(full.lmer)
AICc(reduced.lmer)

```


