---
title: "Parks Canada Broken Group Sites"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

#This code generates plot of trophic cascade between 2013 and 2016 at Parks Canada sites
```{r}
##Parks Canada sea star plot
library(readxl)
library(tidyverse)
library(cowplot)
d<-read_excel("../data/ParksCanada_and_Watson_sites/PRNPR Seastar 2013-2016.xlsx", sheet = "Site-description")
d.avg <- d %>% group_by(Site, Year) %>%
  summarise(Pycno = mean(SUST))

d.avg2 <- d.avg %>% group_by(Year) %>%
  summarise(mean = mean(Pycno), se = sqrt(var(Pycno))/sqrt(5))

ggplot(d.avg, aes(y = log(Pycno+1), x = Year, group = Site))+
  geom_point()+
  #geom_line()+
  theme_cowplot()+
  ylab("log (Number of Pycnopodia)")

ss_plot<-ggplot(d.avg2, aes(x = Year, y = mean))+
  geom_point(size = 3)+
  theme_cowplot()+
  ylim(c=0.2,6)+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2)+
  geom_line(size = 0.2, type = 2)+
  ylab("Pycnopodia density")


parks<-read.csv("../data/ParksCanada_and_Watson_sites/Kelp-density-2013-2016.csv")
parks.summary<-parks %>% 
  group_by(Species,Site,Year) %>%
  summarize(mean.counts=mean(Count_persqm),
            sd.counts=sd(Count_persqm))

parks.summary$ln.counts<-log(parks.summary$mean.counts+1,2)

# change "DK[space]" to "DK" 
parks.summary$Site <- gsub( "DK " , "DK", parks.summary$Site )
Macro.summary <- parks.summary[parks.summary$Species=="MACRO",]
Macro.summary2 <- Macro.summary %>% group_by(Year) %>%
  summarise(mean = mean(mean.counts), se = sqrt(var(mean.counts))/sqrt(5))

par(mfrow=c(1,1))

MP_plot<-ggplot(Macro.summary2, aes(x = Year, y = mean))+
  geom_point(size = 3)+
  theme_cowplot()+
  ylim(c=0,3)+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2)+
  geom_line(size = 0.2)+
  ylab("Macrocystis stipe density")



##########
###########
urch<-read_excel("../data/ParksCanada_and_Watson_sites/PRNPR Red Sea Urchin 2013-2016.xlsx", sheet = "Density")
#ggplot(urch, aes(x = Year, y = log(`Ave density 60m2`+1), color = Site))+
 # geom_point(size = 2.5)+
  #geom_line(size = 1)+
  #scale_color_manual(values = c("black", "black","black","black","black","darkgrey"))+
  #theme_cowplot(10)

urch.sum <- urch %>% group_by(Year) %>%
  summarise(mean = mean(`Ave density 60m2`), se =  sqrt(var(`Ave density 60m2`))/sqrt(5))

urchin_plot<-ggplot(urch.sum, aes(x = Year, y = mean))+
  geom_point(size = 3)+
  theme_cowplot()+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2)+
  geom_line(size = 0.2)+
  ylab("Red urchin density")

plot_grid(ss_plot, urchin_plot, MP_plot, ncol =1)

  library(glmmADMB)


```

#Watson sites urchin abundance through time

```{r}
WatData<-read_csv("../data/ParksCanada_and_Watson_sites/WatsonPSData.csv")
#WatData<-WatData %>% filter(YEAR > 2005) 
WatData<-WatData %>% filter(Site == "Wizard") 
ggplot(WatData, aes(x = YEAR, y = URCHINS, group = Site, color = Site))+
  geom_point(size=2)+
  geom_smooth()+
  theme_cowplot()+
  scale_color_manual(values = c("black"))+
  ylim(c(0,250))
  scale_x_continuous(breaks = c(2006,2008,2010,2012,2014,2016,2018,2020))


```

