---
title: "Spatial patterns of environmental drivers"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## 2019 iButton Data
#This script creates a plot of average temperature versus distance from open coast (data from summer 2019)
```{r}

library(ggrepel)
library(ggthemes)
library(tidyverse)
load(file="./data/spatial_env_data/2019_iButtons_by_day_1m.RData")
my.ylab = expression(atop(paste("Mean Daily Water Temperature, ", degree,"C"), "(+/- Min., Max.)"))
p <- ggplot(subset(sum_by_site_1m, water %in% c("water")), mapping = aes(x = dist_in_sound, y = mean_mean_daily_temp_c)) +
  geom_smooth(method=lm, color = "black") +
  geom_point() +
  geom_pointrange(aes(ymin=mean_min_daily_temp_c, ymax=mean_max_daily_temp_c)) +
   labs(y= my.ylab, x = "Distance into sound (m)")
  
p + theme_classic()



```

## 1980s Druehl NO3 Data
#This creates a plot of nitrate vs distance from open coast

```{r}
load(file="./data/spatial_env_data/Druehl_no3_1980.RData")


druehl_nutrients_1980_means <- druehl_nutrients_1980 %>% group_by(site, depth, month) %>% summarize(mean_no3 = mean(no3, na.rm = T))

druehl_nutrients_1980_means <- druehl_nutrients_1980_means  %>% 
  left_join(sites, by = "site")
druehl_nutrients_1980_means$dist_sound_km <- druehl_nutrients_1980_means$dist_sound/1000

nutrients.means.0m <- filter(druehl_nutrients_1980_means, depth == 0|depth == 4)
nutrients.means.4m <- filter(druehl_nutrients_1980_means, depth == 4)

p1<-ggplot(nutrients.means.0m, aes(x = dist_sound_km,y=mean_no3, color = as.factor(depth))) + geom_point()+
  scale_color_manual(values = c("black","grey")) +
  geom_smooth(method = "nls", formula=y ~ (a*exp(-b * x)),method.args = list(start = c(b = 0.01, a = 10)), size=1, se = FALSE)+
  xlim(c(2,16.5)) 

p1 <- p1 + theme_cowplot(8)
p1
```

```

